### ISSUE TITLE
Failed to spawn command Error

### ISSUE THREAD

**Issue by danafarhat** [AtomLinter/linter-ruby#141]
I am getting this error constantly every time I edit a ruby file. Cannot fix it. Please help.
/Users/danafarhat/.atom/packages/linter/lib/linter-registry.js:159 
[Linter] Error running Ruby Error: Failed to spawn command `/opt/rubies/2.3.3/bin/ruby`. Make sure `/opt/rubies/2.3.3/bin/ruby` is installed and on your PATH   at /Users/danafarhat/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.js:130:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Arcanemagus** [comment]
Is `/opt/rubies/2.3.3/bin/ruby` a valid executable?

**Comment by danafarhat** [comment]
No

**Comment by Arcanemagus** [comment]
You can either change the executable path in the settings to the full path to `ruby` (e.g. the result of `which ruby`), or leave it as the default and launch Atom from an environment where `ruby` resolves to the correct Ruby interpreter.
