### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by johand** [AtomLinter/linter-ruby#23]
**Atom Version**: 1.0.5
**System**: linux 3.14.46-gentoo
**Thrown From**: [linter-ruby](https://github.com/AtomLinter/linter-ruby) package, v1.0.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn ENOTDIR
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /home/foo/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:100:28
    at Object.module.exports.Helpers._exec (/home/foo/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:57:14)
    at Object.module.exports.Helpers.exec (/home/foo/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:27:19)
    at Object.lint (/home/foo/.atom/packages/linter-ruby/lib/main.js:43:24)
    at Promise.then._this.emitter.emit.linter (/home/foo/.atom/packages/linter/lib/linter-registry.coffee:95:31)
```

### Commands

```
     -0:03.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*~",
      "#~"
    ],
    "disabledPackages": [
      "metrics",
    ]
  },
  "linter-ruby": {
    "rubyExecutablePath": "/home/foo/.rbenv/shims/ruby"
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.21.0
linter, v1.3.2
linter-haml, v1.0.0
linter-ruby, v1.0.0
ruby-block, v0.3.5

# Dev
No dev packages
```

**Comment by k2b6s9j** [comment]
Is `/home/foo/.rbenv/shims/ruby` a directory or a binary? The latest update it requires the config setting to be the binary you wish linter to run.

**Comment by johand** [comment]
it's a binary
```sh
file ~/.rbenv/shims/ruby
/home/foo/.rbenv/shims/ruby: a /usr/bin/env bash script, ASCII text executable
```

**Comment by k2b6s9j** [comment]
Hmm... That shouldn't be happening. I'll take a closer look in the morning. Thanks for reporting!

**Comment by mupkoo** [comment]
The problem is that the `cwd` is set to the file.

```javascript
  provideLinter: () => {
    const helpers = require("atom-linter");
    const path = require('path');
    const regex = "(?<file>.+):(?<line>\\d+):\\s*(?<type>[\\w\\s\\-]+)[:,]?\\s*(?<message>.+)";
    return {
      grammarScopes: ["source.ruby", "source.ruby.rails", "source.ruby.rspec"],
      scope: "file",
      lintOnFly: true,
      lint: (activeEditor) => {
        const command = atom.config.get("linter-ruby.rubyExecutablePath");
        const file = activeEditor.getPath();

        // Get the folder using path
        const cwd = path.dirname(file);

        const args = ["-wc", file];

        return helpers.exec(command, args, {stream: "stderr", cwd: cwd}).then((output) => {
          helpers.parse(output, regex);
        });
      }
    };
  }
```

but then I get the following error

```
Failed to spawn command ~/.rbenv/shims/ruby. Make sure ~/.rbenv/shims/ruby is installed and on your PATH
```

**Comment by k2b6s9j** [comment]
D'oh! Thanks @mupkoo.

**Comment by mupkoo** [comment]
Any tip how to get it working with rbenv.

_Failed to spawn command ~/.rbenv/shims/ruby. Make sure ~/.rbenv/shims/ruby is installed and on your PATH_

I am not sure if this is related to main linter package or even Atom

**Comment by mupkoo** [comment]
The old linter used to work with the home directory prefix `~`, but looks like for the current version, you should supply the full path, for example `/Users/Mupko/.rbenv/shims/ruby`

**Comment by AgentAntelope** [comment]
I'm getting this issue with rvm too, supplying the full path doesn't help.

**Comment by zargony** [comment]
Same issue here. My Ruby executable path is set to `/usr/local/var/rbenv/shims/ruby` (which is a binary)

**Comment by cassianoleal** [comment]
Same issue with either chruby/ruby-install or the stock OS X Ruby.

**Comment by ahmetabdi** [comment]
@mupkoo :shipit:

**Comment by mupkoo** [comment]
Have you applied the `cwd` fixed from above?

**Comment by cassianoleal** [comment]
With that patch I get this:
![screen shot 2015-08-07 at 14 57 17](https://cloud.githubusercontent.com/assets/399431/9137279/8cc35c0c-3d14-11e5-90aa-ee964272e1e2.png)

**Comment by bernardogfilho** [comment]
Same here, my path is in `.../.rvm/rubies/ruby-2.2.0/bin/ruby` which is a binary.

**Comment by bogem** [comment]
Thanks, @mupkoo !!
It's working for me (Mac OS X 10.10.4; Atom 1.0.5)

**Comment by giannisp** [comment]
Had the same issue on OS X and rvm, the latest patch does work.
However for some reason it doesn't seem to linter "on the fly", it is only working "on save".
(OS X 10.10.4, Atom 1.0.5, Linter 1.3.2)

**Comment by ricsdeol** [comment]
Same problem with me.

The problem happened always on save file.

**Atom Version**: 1.0.3
**System**: elementary OS
**Thrown From**: [linter-ruby](https://github.com/AtomLinter/linter-ruby) package, v1.0.0


### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /opt/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn ENOTDIR
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/atom/resources/app.asar/src/buffered-process.js:52:14)
  at /home/ricardoleite/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:40:30
  at Object.module.exports.Helpers._exec (/home/ricardoleite/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:22:16)
  at Object.module.exports.Helpers.exec (/home/ricardoleite/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:13:13)
  at Object.lint (/home/ricardoleite/.atom/packages/linter-ruby/lib/main.js:43:24)
  at Promise.then._this.emitter.emit.linter (/home/ricardoleite/.atom/packages/linter/lib/linter-registry.coffee:57:22)
  at LinterRegistry.triggerLinter (/home/ricardoleite/.atom/packages/linter/lib/linter-registry.coffee:56:16)
  at /home/ricardoleite/.atom/packages/linter/lib/linter-registry.coffee:50:17
  at Array.map (native)
  at /home/ricardoleite/.atom/packages/linter/lib/linter-registry.coffee:48:27
  at process._tickCallback (node.js:367:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-erb",
      "atom-ctags",
      "autocomplete-elixir"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/ricardoleite/src"
  },
  "linter-ruby": {
    "rubyExecutablePath": "/home/ricardoleite/.rvm/rubies/default/bin/ruby"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-zeal, v0.1.3
atomatigit, v1.5.4
autocomplete-ctags, v0.3.1
autocomplete-haskell, v0.4.5
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
color-picker, v2.0.11
css-snippets, v0.8.0
ctags-status, v1.3.3
docs-snippets, v0.8.0
file-icons, v1.6.3
git-log, v0.4.1
git-tab-status, v1.9.2
gulp-snippets, v0.6.1
haskell-ghc-mod, v0.8.8
html-id-class-snippets, v1.4.1
ide-haskell, v0.7.1
language-diff, v0.3.0
language-gitignore, v0.2.0
language-haskell, v1.3.0
language-txt2tags, v0.3.0
linter, v1.3.4
linter-coffeelint, v1.0.2
linter-haml, v1.0.0
linter-js-yaml, v1.1.1
linter-jshint, v1.1.5
linter-less, v2.0.3
linter-rubocop, v0.3.1
linter-ruby, v1.0.0
linter-tidy, v1.0.1
local-history, v3.2.3
merge-conflicts, vundefined
minimap, v4.12.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-pigments, v0.1.3
minimap-selection, v4.3.0
pigments, v0.9.3
rspec-snippets, v0.4.0
ruby-block, v0.3.5
spotify-linux, v0.3.2
symbols-tree-view, v0.9.3
sync-settings, v0.6.0
tab-smart-sort, v0.1.4
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by HeartBreakOne** [comment]
I had the same problem but my Ruby exec path was `/home/victor/.rbenv/shims/ruby/`.
Then i switched to `/home/victor/.rbenv/shims/ruby`, and the error went away.

**Comment by djavier** [comment]
This should not be closed, after installing the last update still having the same `ENOTDIR` error when saving the file.

Atom Version: 1.0.5
System: OS X Yosemite 10.10.4
Thrown From: linter-ruby package, v1.0.2
Ruby: RVM (1.26.11)

***PATH***: `/Users/DJ/.rvm/rubies/ruby-2.1.5/bin/ruby`

***FILE TYPE*** : `/Users/DJ/.rvm/rubies/ruby-2.1.5/bin/ruby: Mach-O 64-bit executable x86_64`

***Stack Trace***

         Error: spawn ENOTDIR
          at exports._errnoException (util.js:734:11)
          at ChildProcess.spawn (child_process.js:1145:11)
          at Object.exports.spawn (child_process.js:977:9)
          at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
          at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
          at /Users/DJ/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:40:30
          at Object.module.exports.Helpers._exec (/Users/DJ/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:22:16)
          at Object.module.exports.Helpers.exec (/Users/DJ/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:13:13)
          at Object.lint (/Users/DJ/.atom/packages/linter-ruby/lib/main.js:43:24)
          at Promise.then._this.emitter.emit.linter (/Users/DJ/.atom/packages/linter/lib/linter-registry.coffee:55:22)
          at LinterRegistry.triggerLinter (/Users/DJ/.atom/packages/linter/lib/linter-registry.coffee:54:16)
          at /Users/DJ/.atom/packages/linter/lib/linter-registry.coffee:48:17
          at Array.map (native)
          at /Users/DJ/.atom/packages/linter/lib/linter-registry.coffee:46:27`
