### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by otzy007** [AtomLinter/linter-ruby#29]
Hi,

I'm getting this error every time it checks a file after updating to the latest linter-ruby and latest atom.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-ruby](https://github.com/AtomLinter/linter-ruby) package, v1.0.1

### Stack Trace

Uncaught Error: spawn EACCES

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at /Users/andrei/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:40:30
  at Object.module.exports.Helpers._exec (/Users/andrei/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:22:16)
  at Object.module.exports.Helpers.exec (/Users/andrei/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:13:13)
  at Object.lint (/Users/andrei/.atom/packages/linter-ruby/lib/main.js:45:24)
  at Promise.then._this.emitter.emit.linter (/Users/andrei/.atom/packages/linter/lib/linter-registry.coffee:57:22)
  at LinterRegistry.triggerLinter (/Users/andrei/.atom/packages/linter/lib/linter-registry.coffee:56:16)
  at /Users/andrei/.atom/packages/linter/lib/linter-registry.coffee:50:17
  at Array.map (native)
  at /Users/andrei/.atom/packages/linter/lib/linter-registry.coffee:48:27
  at process._tickCallback (node.js:367:9)

```

### Commands

```
     -1:46.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.5.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -1:35.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:26.5.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:24.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:19.1.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
  2x -1:17.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:02.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:01.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  9x -1:01.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:04.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "RubyMotion"
    ]
  },
  "linter-ruby": {
    "rubyExecutablePath": "/Users/andrei/.rvm/rubies/ruby-2.1.6/bin"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
compare-files, v0.6.2
cucumber, v0.5.0
git-log, v0.4.1
language-haml, v0.21.0
language-html, v0.40.1
language-latex, v0.6.1
language-mustache, v0.12.0
language-rust, v0.4.4
language-slim, v0.5.0
linter, v1.3.4
linter-coffeescript, v1.0.0
linter-erb, v0.1.1
linter-haml, v1.0.0
linter-htmlhint, v0.1.1
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
linter-slim, v1.0.0
ruby-block, v0.3.5

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
It's because your `rubyExecutablePath` is a directory, not a file.

**Comment by otzy007** [comment]
yeah. Noob mistake :))
Thank you
