### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by johand** [AtomLinter/linter-ruby#31]
**Atom Version**: 1.0.7
**Linter-ruby version**:  v1.0.2

```
TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:680:23)
    at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/usr/share/atom/resources/app.asar/src/display-buffer.js:820:35)
    at TextEditor.module.exports.TextEditor.indentLevelForLine (/usr/share/atom/resources/app.asar/src/text-editor.js:2250:33)
    at TextEditor.module.exports.TextEditor.indentationForBufferRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2222:19)
    at Object.module.exports.Helpers.rangeFromLineNumber (/home/foo/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:131:31)
    at /home/foo/.atom/packages/linter-ruby/lib/main.js:53:30
    at Array.forEach (native)
    at /home/foo/.atom/packages/linter-ruby/lib/main.js:47:33
```

**Comment by mneumark** [comment]
I'm getting the same thing. I started getting:
```
TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:680:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:820:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2312:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2284:19)
  at Object.module.exports.Helpers.rangeFromLineNumber (/Users/mneumark/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.coffee:55:30)
  at /Users/mneumark/.atom/packages/linter-ruby/lib/main.js:53:30
  at Array.forEach (native)
  at /Users/mneumark/.atom/packages/linter-ruby/lib/main.js:47:33
```

It seems to be triggered after I delete an empty line. When I go from this:
```ruby
    it 'should include status' do

      first_report
    end
```
to this:
```ruby
    it 'should include status' do
      first_report
    end
```

I get the above error.

If it helps, this is on a Mac running 1.0.8 in Mac OS X 10.10.5

**Comment by relaxdiego** [comment]
I also experience the same error. It was triggered by a missing `end` somewhere in the code.

**Comment by k2b6s9j** [comment]
I just published an update? Mind testing again?

**Comment by mneumark** [comment]
I'll let you know on tuesday

**Comment by johand** [comment]
for now works for me, thank you. :+1:

**Comment by k2b6s9j** [comment]
Thanks! Closing.
