### ISSUE TITLE
Failed to activate the linter-ruby package

### ISSUE THREAD

**Issue by zhuoerri** [AtomLinter/linter-ruby#56]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [linter-ruby](https://github.com/AtomLinter/linter-ruby) package, v1.2.1

### Stack Trace

Failed to activate the linter-ruby package

```
At packageName is required

Error: packageName is required
    at Object.install (/Users/erri/.atom/packages/linter-csslint/node_modules/atom-package-deps/lib/main.js:19:27)
    at Object.activate (/Users/erri/.atom/packages/linter-ruby/lib/main.js:21:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -8:23 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:15.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:32.4.0 git-plus:menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -4:30.7.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:03.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 11x -2:29.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.4.2
autocomplete-ruby, v0.1.0
emmet, v2.3.17
git-log, v0.4.1
jshint, v1.8.3
linter, v1.11.3
linter-csslint, v1.2.0
linter-jshint, v1.2.2
linter-ruby, v1.2.1
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like for some reason Atom is trying to use the `atom-package-deps` module installed within `linter-csslint`, which must be from the old v2.x.x branch still. The odd thing is that your package list shows `linter-csslint` as being at v1.2.0, which should be using the current version.

Can you try going into `~/.atom/packages/linter-csslint` and typing `apm rebuild` in a terminal? If you have `node` installed on your system it would be interesting to see the output of `npm list --depth=0` in that folder before and after you run `apm rebuild`.

**Comment by zhuoerri** [comment]
I just uninstall all packages and reinstall them, and fixed.
