### ISSUE TITLE
Uncaught Error: spawn EINVAL

### ISSUE THREAD

**Issue by brodock** [AtomLinter/linter-ruby#73]
[Enter steps to reproduce below:]
1. hit CMD+S in a ruby file

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-ruby](https://github.com/AtomLinter/linter-ruby) package, v1.2.2
### Stack Trace

Uncaught Error: spawn EINVAL

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EINVAL
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/brodock/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.js:152:75
    at Object.exec (/Users/brodock/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.js:118:10)
    at Object.exec (/Users/brodock/.atom/packages/linter-ruby/node_modules/atom-linter/lib/index.js:158:18)
    at Object.lint (/Users/brodock/.atom/packages/linter-ruby/lib/main.js:43:24)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/brodock/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/brodock/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/brodock/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/brodock/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/brodock/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:34.4.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".idea",
      ".bundle"
    ],
    "projectHome": "/Users/brodock/Projetos",
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter-ruby": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
If you put the results of `which ruby` into the Executable Path configuration option, do things start working for you?

**Comment by brodock** [comment]
@Arcanemagus no :/

There is one more thing that may be worth mentioning, my default shell is `fish`.

**Comment by Arcanemagus** [comment]
@steelbrain Could this be messing with our workaround for the empty environment on OS X?

**Comment by steelbrain** [comment]
@brodock Can you please help us debug this by adding a `console.log` of options in `exec` in `/Users/brodock/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.js`

**Comment by jamtur01** [comment]
Same issue - my shell is also Fish.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, will gladly look into this further if one of you can try the debugging steps @steelbrain requested above!
