### ISSUE TITLE
Failed to activate the linter-ruby package

### ISSUE THREAD

**Issue by ballo009** [AtomLinter/linter-ruby#82]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Unknown Windows Version
**Thrown From**: [linter-ruby](https://github.com/AtomLinter/linter-ruby) package, v1.2.2
### Stack Trace

Failed to activate the linter-ruby package

```
At Unexpected token ILLEGAL

SyntaxError: Unexpected token ILLEGAL
    at Module._compile (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\CF049\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
autocomplete-paths, v1.0.2
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.9
git-log, v0.4.1
go-to-view, v0.3.0
highlight-column, v0.5.1
highlight-line, v0.11.1
language-haml, v0.24.0
language-slim, v0.5.0
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-haml, v1.2.0
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-sass-lint, v1.4.0
linter-slim, v1.0.0
linter-tidy, v2.1.0
minimap, v4.23.4
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-pigments, v0.2.0
monokai, v0.18.0
pigments, vundefined
regex-railroad-diagram, v0.16.0
release-notes, v0.53.0
ruby-block, v0.3.5
script, vundefined
slim-language, v2.2.0
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2
tualo-git-context, v0.6.17

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Marking this as closed, if you are still experiencing this issue please report back after making sure Atom and `linter-ruby` are fully up to date, thanks!
